[build]
  # Directorio donde está el frontend
  base = "frontend/"
  # Comando para construir la aplicación
  command = "pnpm install && pnpm run build"
  # Directorio donde están los archivos construidos
  publish = "dist/"

[build.environment]
  # Versión de Node.js
  NODE_VERSION = "20.11.1"
  # Variables de entorno para el build
  VITE_API_URL = "https://tu-backend-url.herokuapp.com"

# Configuración para SPA (Single Page Application)
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

# Headers de seguridad
[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "DENY"
    X-XSS-Protection = "1; mode=block"
    X-Content-Type-Options = "nosniff"
    Referrer-Policy = "strict-origin-when-cross-origin"

# Headers para archivos estáticos
[[headers]]
  for = "/assets/*"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

